### ISSUE TITLE
Improve writing interface

### ISSUE THREAD

**Issue by emvigo** [emvigo/turbodiary#23]
A huge improvement for PLog would be having an editor-like interface when writing a new entry, which even shows the character count wrt the log character limit and shows other info that might be relevant when adding a new entry.

**Comment by bderrly** [comment]
Any reason to not use $EDITOR or $VISUAL?

**Comment by emvigo** [comment]
> Any reason to not use $EDITOR or $VISUAL?

AFAIK, using $EDITOR/$VISUAL would require storing the new entry into e.g. a tmpfile that PLog would read from and delete (using "shred"?). That would work as a charm for non-encrypted journals, but not for encrypted ones, for which entries should never leave PLog's memory, let alone be written into a file (regardless of being a tmpfile). I know PLog is not critical software (at all!), but I want encryption done correctly for this project. Unless there's a way to pipe out the contents from an editor directly into another program, I think there's no other route than writing a basic editor UI. (And the current situation is just awful).

**Comment by emvigo** [comment]
Superseeded by #41. Closing.
