### ISSUE TITLE
Review #include directives

### ISSUE THREAD

**Issue by emvigo** [emvigo/turbodiary#46]
It's pretty normal that in any project #include's become cluttered, some are not even needed anymore, and some things may even be missing even if we're compiling with extra warnings. [`deheader'](http://www.catb.org/~esr/deheader/) shows some interesting results, although some seem to be false positives.

Using the "good first issue" for the first time, in case someone's looking for something easy to contribute with (idk how effective these tags are).

**Comment by mahditakrim** [comment]
Hi @emvigo,
It's my first time contributing (tags are effective), I read some of your code and README file and figured out what is going on, really cool project especially written in C .

So, may I work on this issue if you explain what you really need to be done with it ?

**Comment by emvigo** [comment]
> Hi @emvigo,
> It's my first time contributing (tags are effective), I read some of your code and README file and figured out what is going on, really cool project especially written in C .
> 
> So, may I work on this issue if you explain what you really need to be done with it ?

Hi @mahditakrim,
Thanks for your interest!

This issue is very simple: it's about removing all unneeded include directives from source and header files and possibly adding some that may ensure better cross-compatibility, bit with a couple of caveats:

* Turbo Diary headers **must** be self-contained, i.e. they must include all other headers that are required for all definitions to be compilable on their own. This means that you should never assume that a header included before will solve anything for the one you're working on.
* The convention the project follows regarding header includes is: 1) local defines, 2) local headers (in alphabetical order), 3) system+standard headers (in alphabetical order).
* Zero warnings: commits should be compilable with make with zero warnings.
* I'd prefer that the PR was just one single commit (squash/rebase your branch before submitting a PR).

I'll be sort of offline during this weekend, so I may not be able to reply back to you as quick as I wished to. I'll try my best though to take a look at any further comments you may have :)

Thank you!

**Comment by mahditakrim** [comment]
Dear @emvigo,
First of all thanks for your description, I will try my best working on it.

Questions:
1. I literally don't know how to build the project (dependency trouble) ?
2. Do you have any format for PR commit messages (mentioning the issue and etc...) ?
3. Can I suggest some option for the project ? (I know it's too early :D)

By the way, have a nice weekend.

**Comment by emvigo** [comment]
> Questions:
> 
> 1. I literally don't know how to build the project (dependency trouble) ?

What's the dependency that's not working?

1. GNU Make
2. pkgconf
3. OpenSSL development headers and runtime library
4. PCRE2 development headers and runtime library

I assume you're using a reasonably well-known Linux distribution. It's been tested under Debian, Ubuntu, Arch, and even under Termux for Android. I bet it works under Fedora, OpenSUSE, and RPM-based distros as well, but no testing has been done on those distros. OS X and Windows are not and will not be supported.

To compile, just run ```make``` in a terminal.

> 2. Do you have any format for PR commit messages (mentioning the issue and etc...) ?
Not really, except that the final commit should use "Closes #46". That allows GitHub to automatically close the issue when the branch is merged into master. Apart from that, as long as the message is descriptive, 

> 3. Can I suggest some option for the project ? (I know it's too early :D)
Open all the Issues you like, they're free! :D (one Issue per feature, though, and label them as an "enhancement"). That's what FOSS is about, isn't it? And feel free to send PRs too if you want to discuss code.

> By the way, have a nice weekend.
You too!

**Comment by mahditakrim** [comment]
Dear @emvigo ,
I am still not able to build the project.
I installed all the dependencies (however I still can't see pcre2-utils by 'which' command) and tried to build the project using 'make' command but got these lines from it =>

Package openssl was not found in the pkg-config search path.
Perhaps you should add the directory containing `openssl.pc'
to the PKG_CONFIG_PATH environment variable
No package 'openssl' found
Package openssl was not found in the pkg-config search path.
Perhaps you should add the directory containing `openssl.pc'
to the PKG_CONFIG_PATH environment variable
No package 'openssl' found
Package libpcre2-8 was not found in the pkg-config search path.
Perhaps you should add the directory containing `libpcre2-8.pc'
to the PKG_CONFIG_PATH environment variable
No package 'libpcre2-8' found
Package libpcre2-8 was not found in the pkg-config search path.
Perhaps you should add the directory containing `libpcre2-8.pc'
to the PKG_CONFIG_PATH environment variable
No package 'libpcre2-8' found
cc -c crypt.c -Wall -Wextra -pedantic -std=c11    -DTDIARY_RELEASE=\"0.4.0\"
In file included from crypt.c:16:0:
crypt.h:19:10: fatal error: openssl/evp.h: No such file or directory
 #include <openssl/evp.h>
          ^~~~~~~~~~~~~~~
compilation terminated.
Makefile:56: recipe for target 'crypt.o' failed
make: *** [crypt.o] Error 1

I got to mention that I have openssl installed ('which' command says that) .
Could you please help me ;D

**Comment by emvigo** [comment]
Hi,
If you're using Debian or any Debian-based distribution, you need the *-dev packages to get the pkg-config files installed: libpcre2-dev and libssl-dev. These packages provide the *.pc files as well. Turbo Diary has been tested on Debian(-based) distributions. Other distributions don't split runtime and development packages like this.

Does it work after installing these packages?

**Comment by mahditakrim** [comment]
I got linux mint, so how to install these packages?

**Comment by RibalGZ** [comment]
Install libpcre2-dev and libssl-dev with the package manager, both available in the "community" repo:
https://community.linuxmint.com/software/view/libpcre2-dev
https://community.linuxmint.com/software/view/libssl-dev

**Comment by mahditakrim** [comment]
> Install libpcre2-dev and libssl-dev with the package manager, both available in the "community" repo:
> https://community.linuxmint.com/software/view/libpcre2-dev
> https://community.linuxmint.com/software/view/libssl-dev

Thanks !
