### ISSUE TITLE
Max character

### ISSUE THREAD

**Issue by mahditakrim** [emvigo/turbodiary#56]
@emvigo ,
Where do you use max character of text input in the code ?

**Comment by emvigo** [comment]
Hm, first: 'Issues' is for bugs, documentation issues, and discussing feature requests. If you have any questions on any contributor's code, send an email to the contributor (look at the git logs for my email, but first use 'git blame' to know who wrote what).

I'm not sure if I understand your question, though. If you're referring to where the maximum character is set, that information is stored in the 'entrysize' field of the 'tdobj' type (td.h for definition, td.c for implementation). However, that is populated in many ways depending on what you're doing with Turbo Diary; e.g. when reading a file, that's read from the (post-decryption) string representation using PCRE2; when creating a new diary, that information is provided by the user.

Please, further discussion on clarifying how the code works will be much easier by email. Closing this issue.

**Comment by mahditakrim** [comment]
Ok, I'm so noob in this area. :disappointed:
