### ISSUE TITLE
Adding a backup option

### ISSUE THREAD

**Issue by mahditakrim** [emvigo/turbodiary#58]
I thing it's a good idea to make backups from diary files to somewhere else in secure and non secure modes and probably with some routine schedules.

I personally really care about my diaries so I want them to be safe and secure and have them in more than one place.

First I wanted to do it with some extra C script program alongside TB, then I thought it's better to have a backup option built in to the TB ?

**Comment by emvigo** [comment]
Good point. It'd be as trivial as outputting the contents of the file to stdout for exporting and getting it from stdin for importing. If we go for the stdout/stdin route, it's up to the user to use whatever piping/redirection mechanism they like to save things; that'd be nicely Unix-y. What do you think?

**Comment by mahditakrim** [comment]
I'm a little bit confused, what do you mean by letting the user have some piping/redirection mechanism?

**Comment by emvigo** [comment]
Backing up a TD file is essentially cp'ing the file under ~/.turbodiary, so importing/exporting is actually already possible from the OS-side of things. A native import/export mechanism shouldn't be more complex than that. So if we want one, I'd go for an -i/-e pair of flags, such that -i  retrieves the contents of stdin into a file and -e prints the contents of a file to stdout. That'd allow for something as simple as:
```
$ turbodiary -ef whatever > mybackup # exporting
$ turbodiary -if whatever < mybackup # importing
```

**Comment by mahditakrim** [comment]
What I mean for very first move is this:

`$ turbodiary   -Bf   fileName   -Bp   backupPath   -S   0 to 7`

`example =>    $ turbodiary   -Bf   whatever.tdf   -Bp   /home/mahdi/backups   -S   7`

**Comment by emvigo** [comment]
Let me see if I understand well, you mean that -S DAYS gets a number DAYS of days to back up, right? The actual periodic job should be handled by the system, not by the turbodiary binary, IMO, as is the Linux way of doing things. Providing a systemd unit+timer would be awesome because it'd be standard across all major Linux distros.

**Comment by mahditakrim** [comment]
So, for the periodic job, could you give me a clear clue that I can work on this issue?

**Comment by emvigo** [comment]
Hi, for the periodic job, if you know how to write a systemd unit and a sane way to deploy it in any LSB-compliant distro, go for it. I've never done that myself, to be honest.

**Comment by mahditakrim** [comment]
Neither do I, so what to do ?

**Comment by emvigo** [comment]
Let us keep this issue open, meanwhile. Something will occur to us at some point.
