### ISSUE TITLE
Preventing from empty diary text

### ISSUE THREAD

**Issue by mahditakrim** [emvigo/turbodiary#60]
I'm not sure whether it's good to just have a warning message or a message that forces user to enter diary text, because sometimes user may only want to enter the title for some remembrance reason.

So let's first add a warning message that warns user to not let the diary text be empty.

**Comment by emvigo** [comment]
Turbo Diary lets the user to enter an empty entry, but a warning might be helpful.

**Comment by emvigo** [comment]
I've taken my own approach on the matter. Take a look at my issue60 branch and tell me what you think about it. It behaves slightly differently as yours: when the user chooses 'no,' my approach aborts the whole operation (while yours reprompts the user for new text).

**Comment by mahditakrim** [comment]
Dear @emvigo ,
I can't check this out or even contribute for at least 10 days (maybe more), we are in a really sad and tough time in my country and region duo to assassination of our military general .

By the way, thanks for your patience and merry Christmas .
