### ISSUE TITLE
Organizing .c and .h files in separate folders

### ISSUE THREAD

**Issue by mahditakrim** [emvigo/turbodiary#62]
How about to be clean ?!

**Comment by emvigo** [comment]
This is a matter of taste. We're not building a library nor using any Automake-ish tools, so I don't see why we need to have headers separate from source files. I'm not against it either, but I'd like to see what kind of directory structure you're thinking of before deciding anything on the matter.

**Comment by mahditakrim** [comment]
Code grows fast, so I think it's better to have clean file structure at the first steps.
I mean everything in its folder for now, if you think it's an extra move then close this issue.

**Comment by emvigo** [comment]
Closing because it doesn't seem to me like the current codebase requires this. If other elements beside the source code (and the docs) become part of it, I might consider this again.
