### ISSUE TITLE
Turbodiary for Android

### ISSUE THREAD

**Issue by mahditakrim** [emvigo/turbodiary#63]
I think it's cool to have TD in Android devices (not just phones).

We use Android more than laptop and PC's, so lets have an application for this case.
For the very first option, we can set the application to run once in every day (or other time routines) that lets you to enter some diary for the day.

Big one, but cool !

**Comment by emvigo** [comment]
Turbo Diary works perfectly under Termux, so it already runs on Android ;)

If you mean a full Android application, that's way beyond the scope of this project and my skills. If you want to get into that, I'll be glad to see that running. Of course, the license of this project allows for doing that!

**Comment by mahditakrim** [comment]
I definitely meant a whole application but with the same name and manner of turbodiary.
I want other people to write diary in TD not just geeks and programmers.

I will work on it.
