### ISSUE TITLE
turbodiary updater

### ISSUE THREAD

**Issue by mahditakrim** [emvigo/turbodiary#64]
How about to have an updater program alongside TD for easy updating until we reached complete versions ?

**Comment by emvigo** [comment]
No, this would be very, very hard to get right and it'd complicate things a lot. Keeping things up-to-date is a task that distros (or the user) should be in charge of. I'm a firm believer that upstream should never care about this. (Disclaimer: I do mantain the AUR package of Turbo Diary for Arch, but I sort of switch to 'downstream' mode when I update it... one gets used to switching hats like this).
