### ISSUE TITLE
Changing max character limitation messages

### ISSUE THREAD

**Issue by mahditakrim** [emvigo/turbodiary#66]
I think it's better for now (till we reach at some multilingual point) to tell the user that max character limitation is for English characters only.

By changing below messages in TD:
'optional 64 characters' and 'only X characters will be stored'

To:
'optional 64 English characters' and 'only x English characters will be stored'

Any idea on messages ?

**Comment by emvigo** [comment]
I think this is stuff that is better explained in documentation rather than in the program itself. Tagging it as 'docs'.
