### ISSUE TITLE
Posting to social media

### ISSUE THREAD

**Issue by mahditakrim** [emvigo/turbodiary#71]
As a user of TD, sometimes I want to post my diaries to my social media, so I over do it.
Is it possible to post a diary to several social medias (such as Twitter, weblog, Telegram and ...) synchronically ?

**Comment by emvigo** [comment]
That requires getting Turbo Diary to work with all the desired services' APIs, some of which (e.g. Twitter) require you to register your application so that you get a developer API key... Not worth the hassle for the kind of software this is meant to be.
