### ISSUE TITLE
sudo make install

### ISSUE THREAD

**Issue by mahditakrim** [emvigo/turbodiary#73]
'make Install' requires sudo to perform correctly, so this should be added to the README file.

**Comment by emvigo** [comment]
No, that actually depends on how your system is set up and what are you trying to accomplish. You might be installing it by setting a non-default prefix (e.g. Termux or when packaging into a clean chroot). Some systems don't even ship sudo by default (e.g. Debian, Arch). Every user should know which locations require root permissions in their own systems. That's not any project's task.
