### ISSUE TITLE
Another make command

### ISSUE THREAD

**Issue by mahditakrim** [emvigo/turbodiary#75]
I think it is useful to have another make command which can do all three 'make', 'make install' and 'make clean' .

How about to call it 'make autoinstall' ? :nerd_face:

**Comment by emvigo** [comment]
Is it really necessary? In fact, cleaning/purging the build directory makes sense only for developers when you need all object files to be recreated at once (and this is seldomly used even when developing: the whole point of Makefiles is to avoid complete rebuilds as most as possible!). Also, managing permissions in that scenario would be very, very hard, as make install *may* need root permissions (or not) and building shouldn't be done as root; so you shouldn't be using that command as root but somehow be sure that you're installing with the right permissions (and no, putting sudo into a script is the worst thing to do!).
