### ISSUE TITLE
Writing diary from anywhere

### ISSUE THREAD

**Issue by mahditakrim** [emvigo/turbodiary#76]
Is it possible to create a mechanism to write diary to a specific .tdf file from anywhere ?

I mean when you don't have access to your laptop, so you can't write diary and you may forget it till you get access to your device.

**Comment by emvigo** [comment]
It is possible; I've done it. But this has nothing to do with Turbo Diary itself: you can easily do that with standard Linux tools like mounting ~/.turbodiary using sshfs. It's not different than connecting via SSH to edit a file with your favorite text editor or whatever.
