### ISSUE TITLE
Internationalization/localization support

### ISSUE THREAD

**Issue by emvigo** [emvigo/turbodiary#86]
Currently, Turbo Diary solely operates in English. Adding gettext (or preferrably, a similar non-GNU alternative) support would be nice to have. It'd be l10n mostly, but moods would require some amount of sensible i18n.

**Comment by RibalGZ** [comment]
https://github.com/sabotage-linux/gettext-tiny :eyes:

**Comment by emvigo** [comment]
After dealing with Libintl for quite a couple of days and actually getting it to work, I'm baffled about how terribly broken deployment becomes when using it. So I'm giving up on this feature.

Already getting the program to get the correct directory passed to bindtextdomain() so that it works both when installed system-wide *and* within the git clone is a nightmere that needs preprocessor macros being passed from the Makefile. I still don't understand why Libintl makes use of POT files, PO files, and weirdly "compiled" MO files when a simple text database of equivalences for each language generated from each source file itself should be enough (am I about to start a new project here?). Heck, I'm pretty sure that solution can consist just of a very lightweight shared library and one single shell script that generates the barebones database from the source code. But I digress.

Speaking of the Makefile itself. The way GNU Libintl works almost *forces* the developer to get into GNU Autotools. I'm not picky about libraries and tools (this project uses OpenSSL and PCRE2, for instance), but oh boy I'm not getting into GNU Autotools just to please Libintl's poor decisions. Trying to write a sane working Makefile according to the needs of Libintl by hand is possible, but leaves a very, very nasty result if one wants the whole thing be suitable for testing, scalable, and also work when installed on /usr/local... or somewhere else as defined by a package manager.

TBH, GNU is the most sub-standard thing ever seen in the *nix side of things. I won't apologize for this rant I highly doubt anyone will ever read, but I really needed to take this off my chest.
